### ISSUE TITLE
Add Internationalisation

### ISSUE THREAD

**Issue by Lothindir** [cheers-li/cheers-li-app#110]
**Description:**

As a user, I would like to be able to use the app in my native language

Add the possibility to change language within the app or use the device default language as choice

**Tasks**

- [ ] Refactor code to add i18n (i18next plugin)
- [ ] Add possibility to switch language within the app
- [ ] Add multiple languages [fr/it/de]
