### ISSUE TITLE
Add friendships

### ISSUE THREAD

**Issue by Lothindir** [cheers-li/cheers-li-app#14]
**Description:**

As a user, I would like to search and send friend requests to other users. I would like to see the list of users and their feed.

The user should be able to search for other users by using their username. A list with all friends should be added with the possibility of seeing the avatar and username, as well as opting-out of their activity feed. The friends can then be added on the map if they are active.

**[Optional]:**

Add a "close friends" feature or a way to group friends to choose to whom send or receive the notifications.

**Tasks**

- [ ] Add users to the database
- [ ] Add friendship relations to the database
- [ ] Add search and request feature to app (navigation item)
- [ ] Add friends list feature to app

**Requirements:**
- Authentification in place and working (need for the users id and username creation) (#7)
- Navigation working (#6)

**Comment by MrF3lix** [comment]
@Lothindir I've created a table with the friendship connections. 
https://app.supabase.com/project/ckiipzxuiudfldnxkxss/editor/17863

There's also a service already to get the profile of friends. It'll be in this pr: https://github.com/cheers-li/cheers-li-app/pull/22
