### ISSUE TITLE
Add password-based authentication

### ISSUE THREAD

**Issue by Lothindir** [cheers-li/cheers-li-app#36]
**Description:**

As a user, I would like to authenticate with an email and a password without the need to use a third-party website. I would like to register a new account using an email and setting a password.

**Tasks**

- [x] Edit login page to add password field
- [x] Edit register page to add password fields
- [x] Link app to Supabase

**Requirements:**
- [x] #7

**Comment by MrF3lix** [comment]
You can do that with the email but it only supports magic link login.

**Comment by Lothindir** [comment]
Yeah, but as the callback link doesn't work it's easier to just provide a password. And for the testing suite it'll need a email/password entry point (Play Store)

**Comment by Lothindir** [comment]
Wasn't too hard to do anyway. We'll see if we need to remove the magic link or do something about the email confirmation as it can hinder the profile creation id the user has to leave the app to open the mail.
Maybe using Deep Links to redirect directly on the app ?
