### ISSUE TITLE
Add more drink options

### ISSUE THREAD

**Issue by MrF3lix** [cheers-li/cheers-li-app#92]
**Description:**

As a User I would like to see more drink options (water, whiskey, cognac, etc.). Instead of showing all the options at once only the most popular are shown and a button "show more" is added to reveal the other choices.

**Tasks**

- [ ] Find more drink options with emoji or icon?
- [x] Add drink options to DB
- [x] Add "show more button"

**Comment by Lothindir** [comment]
@MrF3lix do we need to keep this issue open to remind us to add more content or can we close it for now ?

**Comment by MrF3lix** [comment]
Nope, we can close it.
