### ISSUE TITLE
Invite to Session 

### ISSUE THREAD

**Issue by MrF3lix** [cheers-li/cheers-li-app#93]
**Description:**

As a user I would like to invite other users to a session. Everyone in the group session should be able to change the name. If a user from outside the group sends a cheersli, everyone within the group session should receive it.

**Tasks**

- [x] Add user - session table
- [x] Show users in a session
- [x] Show image of all users in the session image

**Comment by Lothindir** [comment]
Closed by #109
